### ISSUE TITLE
FetchError: request to https://testnet.koii.network/ failed, reason: connect ENETUNREACH

### ISSUE THREAD

**Issue by sxiii** [koii-network/koii-node#10]
### 🐛 What issue do you have?

```
13:11:36.766 › GETTING MY TASKS
13:11:43.589 › check task submissions
13:12:17.570 › GETTING MY TASKS
13:12:58.257 › GETTING MY TASKS
13:13:14.122 › check task submissions
13:13:38.916 › GETTING MY TASKS
13:13:42.244 › check task submissions
13:13:43.995 › Child process 313069 exited with code 1 and signal null
13:13:45.995 › Killing the process: 313069
13:13:46.016 › Process 313069 terminated
13:14:04.464 › Error fetching the slot: FetchError: request to https://testnet.koii.network/ failed, reason: connect ENETUNREACH 64:ff9b::2dfa:fdf6:443
    at ClientRequest.<anonymous> (/opt/Koii Node/resources/app.asar/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
13:14:07.881 › Error: failed to get balance of account AETXMe2ru68XGFxTRW6wKPJZpQ6zBygJvog8ZLRC8gpN: FetchError: request to https://testnet.koii.network/ failed, reason: connect ENETUNREACH 64:ff9b::2dfa:fdf6:443
    at /opt/Koii Node/resources/app.asar/node_modules/@_koi/web3.js/src/connection.ts:2199:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Connection.getBalance (/opt/Koii Node/resources/app.asar/node_modules/@_koi/web3.js/src/connection.ts:2196:12)
13:14:07.881 › Error occurred in handler for 'GET_ACCOUNT_BALANCE': Error: {"detailed":{},"type":"FETCH_ACCOUNT_BALANCE"}
    at ie (/opt/Koii Node/resources/app.asar/dist/main/webpack:/src/utils/error.ts:5:9)
    at /opt/Koii Node/resources/app.asar/dist/main/webpack:/src/main/controllers/getAccountBalance.ts:30:12
    at Generator.throw (<anonymous>)
    at s (/opt/Koii Node/resources/app.asar/dist/main/webpack:/src/main/controllers/generateSeedPhrase.ts:8:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
13:14:07.882 › Error: failed to get balance of account AETXMe2ru68XGFxTRW6wKPJZpQ6zBygJvog8ZLRC8gpN: FetchError: request to https://testnet.koii.network/ failed, reason: connect ENETUNREACH 64:ff9b::2dfa:fdf6:443
    at /opt/Koii Node/resources/app.asar/node_modules/@_koi/web3.js/src/connection.ts:2199:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Connection.getBalance (/opt/Koii Node/resources/app.asar/node_modules/@_koi/web3.js/src/connection.ts:2196:12)
13:14:07.882 › Error occurred in handler for 'GET_ACCOUNT_BALANCE': Error: {"detailed":{},"type":"FETCH_ACCOUNT_BALANCE"}
    at ie (/opt/Koii Node/resources/app.asar/dist/main/webpack:/src/utils/error.ts:5:9)
    at /opt/Koii Node/resources/app.asar/dist/main/webpack:/src/main/controllers/getAccountBalance.ts:30:12
    at Generator.throw (<anonymous>)
    at s (/opt/Koii Node/resources/app.asar/dist/main/webpack:/src/main/controllers/generateSeedPhrase.ts:8:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
13:14:18.117 › Error: failed to get balance of account Hmg83WnRDM7Qs9XAC179sC4858HWzWQDunFAwabgPXqK: FetchError: request to https://testnet.koii.network/ failed, reason: connect ENETUNREACH 64:ff9b::2dfa:fdf6:443
    at /opt/Koii Node/resources/app.asar/node_modules/@_koi/web3.js/src/connection.ts:2199:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Connection.getBalance (/opt/Koii Node/resources/app.asar/node_modules/@_koi/web3.js/src/connection.ts:2196:12)
13:14:18.118 › Error occurred in handler for 'GET_ACCOUNT_BALANCE': Error: {"detailed":{},"type":"FETCH_ACCOUNT_BALANCE"}
    at ie (/opt/Koii Node/resources/app.asar/dist/main/webpack:/src/utils/error.ts:5:9)
    at /opt/Koii Node/resources/app.asar/dist/main/webpack:/src/main/controllers/getAccountBalance.ts:30:12
    at Generator.throw (<anonymous>)
    at s (/opt/Koii Node/resources/app.asar/dist/main/webpack:/src/main/controllers/generateSeedPhrase.ts:8:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
13:14:19.578 › GETTING MY TASKS
13:14:36.891 › FetchError: request to https://testnet.koii.network/ failed, reason: connect ENETUNREACH 64:ff9b::2dfa:fdf6:443
    at ClientRequest.<anonymous> (/opt/Koii Node/resources/app.asar/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
13:14:39.146 › check task submissions
```

### 🌐 Desktop Node Version

0.6.7

### 🖥️ Operating System

Garuda Linux 

### 🔑 System Key

AETXMe2ru68XGFxTRW6wKPJZpQ6zBygJvog8ZLRC8gpN

### Task ID

2QsiB2jdufTkt1jghMA68eZxQ4tJQb7DBWrnowx1nNeJ

### Steps to reproduce

1. Start client
2. Try running the task "Free Token Task!"
3. It worked for 5 times (I've earned 2.5 KOII), but now it fails-out all the time with error in the UI "Something went wrong. Try running this task again".
4. I've also provided CLI logs for easier debug.
5. Tried disabling IPv6 but it didn't seems to help.

**Comment by sxiii** [comment]
This is resolved now either by itself or devs had fixed something :) So closing.
